### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by yogeek** [FredrikNoren/ungit#1009]
Hello,

First thank you for this beautiful GUI (Git-UI :P)
After installation, I tried to launch it on Ubuntu but I have this message :

```
/usr/local/lib/node_modules/ungit/bin/ungit:29
  let currentUrl = `${config.urlBase}:${config.port}${config.rootPath}`
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

Environment :
```
$ node --version
v4.2.6
```

```
$ uname -a
Linux msi 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/*rele*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

```

Thank you for your help

**Comment by jung-kim** [comment]
Yes this is due to node version being bit out dated.  

Readme is recommending [node.js (≥ 6.11)](https://github.com/FredrikNoren/ungit#installing).

And you may find out more about es6 syntax supports at http://node.green/
