### ISSUE TITLE
Syntax Error let pathToNavigateTo

### ISSUE THREAD

**Issue by RayhanYulanda** [FredrikNoren/ungit#1096]
i got this error when i run 
$ungit

/usr/local/lib/node_modules/ungit/bin/ungit:29
  let pathToNavigateTo = null;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by jung-kim** [comment]
Ungit requires [node >= 6.11](https://github.com/FredrikNoren/ungit#installing) and since `let` is [supported since 6.4](https://node.green/#ES2015-bindings-let).  I think once you upgrade the node version it should be fixed.
