### ISSUE TITLE
new install with template .ungitrc TypeError: Path must be a string

### ISSUE THREAD

**Issue by atomic** [FredrikNoren/ungit#1119]
Got these error on any git directory no matter the states. Tested on node `v9.11.2` and `v10.7.0` without any adblocks.

Logs:
```
Navigate to http://localhost:8080/#/repository?path=%2FUsers%(some path here)
2018-07-30T19:37:40.121Z - warn: Responding with ERROR:  {"stack":"TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.extname (path.js:1376:5)
    at module.exports (/Users/atomic/.nvm/versions/node/v9.11.2/lib/node_modules/ungit/src/utils/file-type.js:7:43)
    at parseFileChanges (/Users/atomic/.nvm/versions/node/v9.11.2/lib/node_modules/ungit/src/git-parser.js:165:19)
    at /Users/atomic/.nvm/versions/node/v9.11.2/lib/node_modules/ungit/src/git-parser.js:171:5
    at Array.forEach (<anonymous>)
    at exports.parseGitLog (/Users/atomic/.nvm/versions/node/v9.11.2/lib/node_modules/ungit/src/git-parser.js:170:8)
    at tryCatcher (/Users/atomic/.nvm/versions/node/v9.11.2/lib/node_modules/ungit/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/atomic/.nvm/versions/node/v9.11.2/lib/node_modules/ungit/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/atomic/.nvm/versions/node/v9.11.2/lib/node_modules/ungit/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/atomic/.nvm/versions/node/v9.11.2/lib/node_modules/ungit/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/atomic/.nvm/versions/node/v9.11.2/lib/node_modules/ungit/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/atomic/.nvm/versions/node/v9.11.2/lib/node_modules/ungit/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/atomic/.nvm/versions/node/v9.11.2/lib/node_modules/ungit/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/atomic/.nvm/versions/node/v9.11.2/lib/node_modules/ungit/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)","message":"The \"path\" argument must be of type string"}
```

**Comment by atomic** [comment]
Issue resolved. The problem is in my `~/.gitconfig` where I set global color configurations like:

[color]
  diff = always
  status = always
  ....'

which messes up the encoding.

**Comment by jung-kim** [comment]
Cool glad to know that it is `.gitconfig` parsing issue. 

I may try to replicate this and see if I can detect this on within the code and handle it differently
