### ISSUE TITLE
error when starting on Ubuntu 16.04

### ISSUE THREAD

**Issue by Chabrier** [FredrikNoren/ungit#1203]
I get this:
```
/usr/local/lib/node_modules/ungit/node_modules/open/index.js:11
const wslToWindowsPath = async path => {
                               ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ungit/bin/ungit:4:14)
```
Dependencies installed:
```
pchabrier@arlaud:~$ uname -a
Linux arlaud 4.4.0-148-generic #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
pchabrier@arlaud:~$ cat /etc/issue
Ubuntu 16.04.6 LTS \n \l

pchabrier@arlaud:~$ nodejs --version
v6.17.1
pchabrier@arlaud:~$ git --version
git version 2.7.4
pchabrier@arlaud:~$ npm --version
3.10.10
pchabrier@arlaud:~$ ungit --version
1.4.44
```

**Comment by ZimGil** [comment]
Looks like an error with the arrow function assignments on Linux in @sindresorhus /[open](https://github.com/sindresorhus/open)

I've recently had this issue at work, we've just changed it to a named function.

**Comment by sindresorhus** [comment]
It’s the `async` keyword.

**Comment by NathanOrme** [comment]
@sindresorhus what needs to happen in that case?

**Comment by whossname** [comment]
this is solved here https://github.com/FredrikNoren/ungit/issues/1204#issuecomment-522127506

**Comment by campersau** [comment]
Yes, @whossname is right, `async` requires a newer node version.
