### ISSUE TITLE
Error on first run：stderr: ...\node_modules\ungit\source\git-parser.js:47

### ISSUE THREAD

**Issue by BruceOuyang** [FredrikNoren/ungit#1280]
```shell
$ ungit
stderr: C:\bruce\envs\nodejs\node_global\node_modules\ungit\source\git-parser.js:47
const fileChangeRegex = /(?<additions>[\d-]+)\t(?<deletions>[\d-]+)\t((?<fileName>[^\x00]+?)\x00|\x00(?<oldFileName>[^\x00]+?)\x00(?<newFileName>[^\x00]+?)\x00)/g;
                        ^

SyntaxError: Invalid regular expression: /(?<additions>[\d-]+)\t(?<deletions>[\d-]+)\t((?<fileName>[^\x00]+?)\x00|\x00(?<oldFileName>[^\x00]+?)\x00(?<newFileName>[^\x00]+?)\x00)/: Invalid group
    at Object.<anonymous> (C:\bruce\envs\nodejs\node_global\node_modules\ungit\source\git-parser.js:47:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\bruce\envs\nodejs\node_global\node_modules\ungit\source\git-api.js:3:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
Stopped keeping ungit alive
```

**Comment by BruceOuyang** [comment]
cause by i have low version of **node** and **npm**, when i finished upgrade, everything is ok.

As the Installing says:

Requires node.js (≥ 10.18.0), npm (≥ 6.13.4, comes with node.js) and git (≥ 1.8.x). To install ungit just type:
```shell
npm install -g ungit
```
