### ISSUE TITLE
Unable to launch ungit; git-parser error after update

### ISSUE THREAD

**Issue by netrbrunet** [FredrikNoren/ungit#1302]
Updated ungit and it will no longer launch. Subsequently updated GitBash on my Windows 10 in order to try and resolve, but the issue persisted. Full removal of the GitBash npm and npm_cache directories and re-install of ungit, but issue persists.
```
r*********t@LT-****** MINGW64 /c/users/r*********t/loader-code (master)
$ stderr: C:\Users\r*********t\AppData\Roaming\npm\node_modules\ungit\source\git-parser.js:47
const fileChangeRegex = /(?<additions>[\d-]+)\t(?<deletions>[\d-]+)\t((?<fileName>[^\x00]+?)\x00|\x00(?<oldFileName>[^\x00]+?)\x00(?<newFileName>[^\x00]+?)\x00)/g;
                        ^

SyntaxError: Invalid regular expression: /(?<additions>[\d-]+)\t(?<deletions>[\d-]+)\t((?<fileName>[^\x00]+?)\x00|\x00(?<oldFileName>[^\x00]+?)\x00(?<newFileName>[^\x00]+?)\x00)/: Invalid group
    at Object.<anonymous> (C:\Users\r*********t\AppData\Roaming\npm\node_modules\ungit\source\git-parser.js:47:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\r*********t\AppData\Roaming\npm\node_modules\ungit\source\git-api.js:3:19)
    at Module._compile (module.js:652:30)
Stopped keeping ungit alive

[1]+  Done                    ungit

```

**Comment by campersau** [comment]
What version of node do you use? >= 10.18 is required. See also https://github.com/FredrikNoren/ungit/issues/1280#issuecomment-588084416 and https://github.com/FredrikNoren/ungit/pull/1256

**Comment by netrbrunet** [comment]
Fantastic, that did it @campersau .
Just installed latest node.js and I'm off and running again.

Was there a way I should have seen that? Anything in the errors or a dependency note when re-installing ungit?

**Comment by campersau** [comment]
Currently we only specify the version here
https://github.com/FredrikNoren/ungit/blob/0a2cafe271da32173a4e0d2d0d99eb6aadbcc792/package.json#L95
but it seems we also need [`engine-strict`](https://docs.npmjs.com/using-npm/config#engine-strict)  to actually show an error message.
