### ISSUE TITLE
Unable to use latest versions of ungit (v1.5.10)

### ISSUE THREAD

**Issue by vitalEol** [FredrikNoren/ungit#1418]
I've been using ungit@v1.5.7 previously without issue
![ungit_v1 5 7](https://user-images.githubusercontent.com/42639787/91976743-5ab50700-ed19-11ea-8e06-417ce146a797.png)

When trying to upgrade to the latest I'm running into problems - it doesn't seem to load any repository
ungit@1.5.10: ![ungit_v1 5 10](https://user-images.githubusercontent.com/42639787/91976756-61dc1500-ed19-11ea-976e-8b4af5650105.png)
ungit@1.5.9: ![ungit_v1 5 9](https://user-images.githubusercontent.com/42639787/91976793-715b5e00-ed19-11ea-9f01-dee2580693f1.png)

My setup is as follows:
- node: v14.9.0
- npm: 6.14.8
- git: git version 2.28.0
- ungit: 1.5.9
- kernel: Linux 4.4.0-187-generic #217-Ubuntu SMP Tue Jul 21 04:18:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- distro: Ubuntu 16.04.7 LTS
- browser: Min v1.7.1 (based on Chromium v61.0.3163.100)

Is there any additional debug options I can enable to see what's going wrong?

**Comment by jung-kim** [comment]
Could you possibly share followings?

1. browser console log output when you navigate to ungit?
2. ungit terminal logs 

Meanwhile, I do have a suspicion that build doesn't run on npm update automatically.  Can you possibly try this?

1. cd to directory that has ungit
2. run `npm build`

**Comment by jung-kim** [comment]
Could you possibly share followings?

1. browser console log output when you navigate to ungit?
2. ungit terminal logs 

Meanwhile, I do have a suspicion that build doesn't run on npm update automatically.  Can you possibly try this?

1. cd to directory that has ungit
2. run `npm build`

**Comment by vitalEol** [comment]
Attached is the console log from min browser (I've removed some paths/titles)
[min_console.log](https://github.com/FredrikNoren/ungit/files/5173144/min_console.log)

Terminal output of running ungit instance
![image](https://user-images.githubusercontent.com/42639787/92208599-6e7c7c80-ee83-11ea-9838-30609ea1abdb.png)
Is there a seperate ungit log file I can upload?

Building ungit in the npm folder doesn't show any errors
![image](https://user-images.githubusercontent.com/42639787/92209093-56f1c380-ee84-11ea-8891-98daaef9a303.png)

**Comment by campersau** [comment]
The browser Min v1.7.1 (based on Chromium v61.0.3163.100) uses a quite old Chromium version from 2017 which might be an issue. We only do tests on chromium versions which puppeteer is using which are quite recent. Which is why I voted for only supporting evergreen browsers [here](https://github.com/FredrikNoren/ungit/pull/1178#issuecomment-552924367) and we should [mention that in the readme](https://github.com/FredrikNoren/ungit/pull/1358#issuecomment-628803777).
In the `min_console.log` are some deprecation warnings, not sure if they are the reason for this issue though.

```
/usr/lib/min/resources/app/node_modules/dexie/dist/dexie.js:sourcemap:420 Promise.on('error') is deprecated. See https://github.com/dfahlander/Dexie.js/wiki/Deprecations.
    at file:///usr/lib/min/resources/app/dist/build.min.js:5:26008
(anonymous) @ /usr/lib/min/resources/app/node_modules/dexie/dist/dexie.js:sourcemap:420
build.min.js:7 {"version":2,"state":{"tasks":[{"name":null,"tabs":[{"url":"http://localhost:8448/#/repository?path=%2Ftmp%2Fungit","title":":( ungit crash ungit < tmp","id":"75276878768479200","lastActivity":1599201640608,"secure":false,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false}],"tabHistory":{"depth":20,"stack":[{"url":"http://localhost:8448/","title":"ungit","id":"73830490537490780","lastActivity":1598358091489,"secure":false,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false},{"url":"http://localhost:8448/","title":"ungit","id":"7636243169077472","lastActivity":1598442444450,"secure":false,"private":false,"readerable":false,"selected":true,"isReaderView":false},{"url":"http://localhost:8448/","title":"ungit","id":"28604682041353400","lastActivity":1599044643599,"secure":false,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false},{"url":"http://localhost:8448/#/","title":"ungit","id":"36429793408764510","lastActivity":1599044825234,"secure":false,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false},{"url":"http://localhost:8448/","title":"ungit","id":"74629337013888220","lastActivity":1599044794134,"secure":false,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false},{"url":"http://localhost:8448/#/repository?path=REMOVED","title":"ungit","id":"72400156260633220","lastActivity":1597051631548,"secure":false,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false},{"url":"http://localhost:8448/#/repository?path=REMOVED","title":"ungit","id":"57328212402806570","lastActivity":1599036826742,"secure":false,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false},{"url":"http://localhost:8448/#/repository?path=REMOVED","title":"ungit","id":"45744263973922590","lastActivity":1599037369543,"secure":false,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false},{"url":"http://localhost:8448/#/repository?path=REMOVED","title":"ungit","id":"20755853797276136","lastActivity":1599036862844,"secure":false,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false},{"url":"http://localhost:8448/#/repository?path=REMOVED","title":"ungit","id":"17901230726515682","lastActivity":1599036864318,"secure":false,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false},{"url":"http://localhost:8448/","title":"ungit","id":"32606391693446056","lastActivity":1599047470875,"secure":false,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false},{"url":"http://localhost:8448/#/repository?path=REMOVED","title":"REMOVED","id":"64168178168628080","lastActivity":1599047487856,"secure":false,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":false,"isReaderView":false},{"url":"http://localhost:8448/#/repository?path=REMOVED","title":"REMOVED","id":"95718773059761070","lastActivity":1599047485961,"secure":false,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":false,"isReaderView":false},{"url":"http://localhost:8448/#/","title":"ungit","id":"48162497400323480","lastActivity":1599047470878,"secure":false,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false},{"url":"http://localhost:8448/#/repository?path=REMOVED","title":"REMOVED","id":"76913241209942670","lastActivity":1599054842119,"secure":false,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false},{"url":"file:///usr/lib/min/resources/app/pages/error/index.html?ec=-102&url=http%3A%2F%2Flocalhost%3A8448%2F%23%2Frepository%3Fpath%3DREMOVED","title":"An error occurred","id":"17249364632960674","lastActivity":1599201279786,"secure":true,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false},{"url":"file:///usr/lib/min/resources/app/pages/error/index.html?ec=-102&url=http%3A%2F%2Flocalhost%3A8448%2F%23%2Frepository%3Fpath%3DREMOVED","title":"An error occurred","id":"45251553350468510","lastActivity":1599055738596,"secure":true,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false},{"url":"file:///usr/lib/min/resources/app/pages/error/index.html?ec=-102&url=http%3A%2F%2Flocalhost%3A8448%2F%23%2Frepository%3Fpath%3DREMOVED","title":"An error occurred","id":"61769094144252160","lastActivity":1599056934512,"secure":true,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false},{"url":"file:///usr/lib/min/resources/app/pages/error/index.html?ec=-102&url=http%3A%2F%2Flocalhost%3A8448%2F%23%2Frepository%3FpathREMOVED","title":"An error occurred","id":"46588597076780000","lastActivity":1599056944799,"secure":true,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":true,"isReaderView":false},{"url":"http://localhost:8448/#/repository?path=%2Ftmp%2Fungit","title":":( ungit crash ungit < tmp","id":"31418862350106356","lastActivity":1599201640615,"secure":false,"private":false,"readerable":false,"backgroundColor":"rgb(26,32,41)","foregroundColor":"white","selected":false,"isReaderView":false}]},"id":"25746430646266892"}],"selectedTask":"25746430646266892"}}
placesWorker.js:3 worker started  4.725
build.min.js:5 database opened  402.32500000000005
bootstrap_node.js:3 worker started
dexie.min.js:sourcemap:1 Promise.on('error') is deprecated. See https://github.com/dfahlander/Dexie.js/wiki/Deprecations.
    at file:///usr/lib/min/resources/app/js/util/database.js:80:15
    at file:///usr/lib/min/resources/app/js/bookmarksHistory/placesWorker.js:7:1
(anonymous) @ dexie.min.js:sourcemap:1
events.js:1 Promise.on('error') is deprecated. See https://github.com/dfahlander/Dexie.js/wiki/Deprecations.
    at file:///usr/lib/min/resources/app/js/util/database.js:80:15
    at file:///usr/lib/min/resources/app/js/bookmarksHistory/placesWorker.js:7:1
(anonymous) @ events.js:1
database.js:77 database opened  90.06
internal/errors.js:77 database opened
```

**Comment by vitalEol** [comment]
Updating to the latest version of min (v1.16 based on chromium v83.0.4103.122) seems to have corrected the issue
![image](https://user-images.githubusercontent.com/42639787/92213434-72ac9800-ee8b-11ea-9f2a-fac1c8484cdb.png)

It may be worthwhile listing the browser versions each release is tested against
