### ISSUE TITLE
Unexpected token '.' on 1.5.23

### ISSUE THREAD

**Issue by NicolasCllt** [FredrikNoren/ungit#1557]
`Setting log level to warn
stderr: /usr/local/lib/node_modules/ungit/node_modules/rimraf/dist/cjs/src/ignore-enoent.js:15
        if (er?.code !== 'ENOENT') {
               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ungit/node_modules/rimraf/dist/cjs/src/rimraf-posix.js:14:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Stopped keeping ungit alive
`
- Node : `v12.22.9`
- Npm : `8.5.1`
- Git : `git version 2.34.1`
- Ungit : `1.5.23+68bfabe6`
- OS : `Ubuntu 22.04.2 LTS`

* Solution : Downgrade ungit to 1.5.22

**Comment by campersau** [comment]
ungit now requires node version 14

**Comment by NicolasCllt** [comment]
Thank you for the answer
