### ISSUE TITLE
ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by bes-internal** [FredrikNoren/ungit#1577]
Ungit trying watch all files in subdirs, ignore .gitignore, and dies. But should only watch to tracked files(git ls-files). Related to #1544
```
2023-10-19T12:54:30.466Z - error: Error: ENOSPC: System limit for number of file watchers reached, watch '/var/www/00host/core/test_38/vendor/local/lib/perl5/site_perl/5.36.1/x86_64-linux/auto/Mozilla/CA'
at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
at Object.watch (node:fs:2442:36)
at /usr/lib64/node_modules/ungit/node_modules/node-watch/lib/watch.js:398:22
    asNativeRecursive (/usr/lib64/node_modules/ungit/node_modules/node-watch/lib/has-native-recursive.js:61:12)
    at Watcher.watchDirectory (/usr/lib64/node_modules/ungit/node_modules/node-watch/lib/watch.js:381:3)
    at /usr/lib64/node_modules/ungit/node_modules/node-watch/lib/watch.js:414:16
    at /usr/lib64/node_modules/ungit/node_modules/node-watch/lib/watch.js:143:35
    at Array.forEach (<anonymous>)
    at /usr/lib64/node_modules/ungit/node_modules/node-watch/lib/watch.js:141:13
    at FSReqCallback.oncomplete (node:fs:189:23)
Stopped keeping ungit alive

```

**Comment by victorbnl** [comment]
Agreed, this is quite annoying. This prevents me from using ungit when working on either Node.JS or Rust projects.

**Comment by jung-kim** [comment]
This is indeed annoying... I've stopped working on ungit but you can get around via doing `ulimit -n 1655350` for now. 

If I remember correctly file watcher is set to not watch ignored files

**Comment by capaj** [comment]
@bes-internal I have also suffered this problem many times. 
It drove me so mad that in the end I had to create my own version of ungit: https://ingit.pages.dev/

would be very interested if it solves the problem with file watchers for you. It did for me
