### ISSUE TITLE
 error: Error: EACCES: permission denied, watch '/home/capaj/work-repos/theguild/graphql-hive/docker/.hive-dev/postgresql/db'

### ISSUE THREAD

**Issue by capaj** [FredrikNoren/ungit#1593]
I am trying to run ungit in this repo:
https://github.com/capaj/graphql-hive

and keep getting this crash:
```
Navigate to http://localhost:8448/#/repository?path=/home/capaj/work-repos/theguild/graphql-hive
2024-06-11T04:57:47.095Z - error: Error: EACCES: permission denied, watch '/home/capaj/work-repos/theguild/graphql-hive/docker/.hive-dev/postgresql/db'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2464:36)
    at tryWatch (/home/capaj/.local/share/pnpm/global/5/.pnpm/node-watch@0.7.4/node_modules/node-watch/lib/watch.js:131:15)
    at /home/capaj/.local/share/pnpm/global/5/.pnpm/node-watch@0.7.4/node_modules/node-watch/lib/watch.js:412:19
    at hasNativeRecursive (/home/capaj/.local/share/pnpm/global/5/.pnpm/node-watch@0.7.4/node_modules/node-watch/lib/has-native-recursive.js:61:12)
    at Watcher.watchDirectory (/home/capaj/.local/share/pnpm/global/5/.pnpm/node-watch@0.7.4/node_modules/node-watch/lib/watch.js:395:3)
    at /home/capaj/.local/share/pnpm/global/5/.pnpm/node-watch@0.7.4/node_modules/node-watch/lib/watch.js:432:16
    at /home/capaj/.local/share/pnpm/global/5/.pnpm/node-watch@0.7.4/node_modules/node-watch/lib/watch.js:153:35
    at Array.forEach (<anonymous>)
    at /home/capaj/.local/share/pnpm/global/5/.pnpm/node-watch@0.7.4/node_modules/node-watch/lib/watch.js:151:13

```

Would be nice if ungit could ignore these errors. This is git ignored directory anyway

**Comment by Lu-Pires** [comment]
did you find out whats causing this? i'm having the same error except for some reason the folder is my games folder (which isnt even located in HOME/user)

**Comment by capaj** [comment]
not really, I just know ungit is spamming new file descriptors.
I am quite sure if you ask claude opus it will be able to solve it.
