### ISSUE TITLE
Cygwin path issue: unable to find git

### ISSUE THREAD

**Issue by muellerj** [FredrikNoren/ungit#164]
I have a Cygwin installation under Win7, 64bit, under which the `child_process` is unable to find git in my path:

``` bash
(~) [master] % ungit
Can't run "git --version". Is git installed and available in your path?
(~) [master] % which git
/usr/bin/git
(~) [master] % echo $PATH
/usr/local/bin:/usr/bin:/ [snip]
```

Any ideas how to debug this issue? How can I look at the `PATH`, that is being searched? I realise that the version requirement is not met with the standard cygwin-git, but it should find the binary regardless.

**Comment by waclaw66** [comment]
Hi.
I have exactly the same problem with the latest version under Mageia 5 linux:

```
[waclaw@server bin]$ ./ungit
error: Can't run "git --version". Is git installed and available in your path?

/usr/local/ungit/src/config.js:198
  throw e;
        ^
TypeError: Object #<Object> has no method 'execSync'
    at Object.<anonymous> (/usr/local/ungit/src/config.js:195:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/ungit/bin/ungit:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

[waclaw@server bin]$ node -e "require('child_process').exec('git --version', function(err, stdout) { console.log(err, stdout); })"
null 'git version 2.7.4\n'
```
Thanks for any help.
