### ISSUE TITLE
"Cannot read property 'indexOf' of undefined" when checkout on ungit 0.10.3

### ISSUE THREAD

**Issue by PennYU** [FredrikNoren/ungit#818]
Hi, I would like to create an issue, "Something went wrong, reload the page to start over." comes up when I make a ”checkout" on ungit 0.10.3. Following is the stack I got from Chrome:

server.js:220 Cannot read property 'indexOf' of undefinedServer._onUnhandledBadBackendResponse @ server.js:220
server.js:225 Error: Backend error: Cannot read property 'indexOf' of undefined
    at Server.query (http://0f7ca0ff-5ff4-458e-8ceb-2c0813528a61-8448.microtools.swarm/js/ungit.js:6325:25)
    at Server.post (http://0f7ca0ff-5ff4-458e-8ceb-2c0813528a61-8448.microtools.swarm/js/ungit.js:6311:8)
    at GraphActions.Checkout.perform (http://0f7ca0ff-5ff4-458e-8ceb-2c0813528a61-8448.microtools.swarm/plugins/graph/graph.bundle.js:291:15)
    at GraphActions.Checkout.GraphActions.ActionBase.doPerform (http://0f7ca0ff-5ff4-458e-8ceb-2c0813528a61-8448.microtools.swarm/plugins/graph/graph.bundle.js:93:8)
    at HTMLDivElement.<anonymous> (http://0f7ca0ff-5ff4-458e-8ceb-2c0813528a61-8448.microtools.swarm/js/ungit.js:28313:62)
    at HTMLDivElement.dispatch (http://0f7ca0ff-5ff4-458e-8ceb-2c0813528a61-8448.microtools.swarm/js/ungit.js:7213:9505)
    at HTMLDivElement.y.handle (http://0f7ca0ff-5ff4-458e-8ceb-2c0813528a61-8448.microtools.swarm/js/ungit.js:7213:6288)
Backend stacktrace:
TypeError: Cannot read property 'indexOf' of undefined
    at /usr/lib/node_modules/ungit/src/git-promise.js:242:15
    at tryCatcher (/usr/lib/node_modules/ungit/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/ungit/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/usr/lib/node_modules/ungit/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/ungit/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/usr/lib/node_modules/ungit/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/usr/lib/node_modules/ungit/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/lib/node_modules/ungit/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/ungit/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)

**Comment by codingtwinky** [comment]
Wow, so fix for this is easy but I'm surprise that `git stash` doesn't have any output.  Even when there are nothing to stash it should have output...

what version of OS and git are you using?

**Comment by codingtwinky** [comment]
I think you could apply changes I made in #819 in `{ungit-dir}/src/git-promise.js` line 242 to hotpatch this problem but this is surprising...

**Comment by PennYU** [comment]
I am using ungit 0.10.3 on an alpine linux 3.4.0, and the alpine linux runs in a docker container.

/service # more /etc/alpine-release
3.4.0
/service # uname -a
Linux de14608395dc 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 Linux
/service #

**Comment by codingtwinky** [comment]
interesting, I might have to play with that OS.  But have you tried to apply the fix I gave you?  I maybe asking too much but if you can confirm it would be great.  or you could also do `ungit --autoStashAndPop=false`

**Comment by PennYU** [comment]
I tried, it worked. and I also tried "git stash", I think it’s something wrong with my repo, following is what I got from ”git stash“

/workspace #
/workspace # r=`git stash`
fatal: bad revision 'HEAD'
fatal: bad revision 'HEAD'
fatal: Needed a single revision
You do not have the initial commit yet
/workspace # echo $r

/workspace #
/workspace #

**Comment by codingtwinky** [comment]
I think you are working with bare repo which means I would need to add more stuff to bare repo test suite so this won't happen again.  

Thanks, will be closing this for now and this issue will be fixed with ungit v0.10.3+
