### ISSUE TITLE
v1.0.0 - exception thrown at launch

### ISSUE THREAD

**Issue by evanoloughlin** [FredrikNoren/ungit#845]
Versions
- ungit : 1.0.0
- node : v0.10.25
- npm : 1.3.10
- OS: ubuntu 14.04

When trying to launch ungit i get the following:
```
user@developer-PC:~$ ungit
error: Can't run "git --version". Is git installed and available in your path?

/usr/local/lib/node_modules/ungit/src/config.js:195
  throw e;
        ^
TypeError: Object #<Object> has no method 'execSync'
    at Object.<anonymous> (/usr/local/lib/node_modules/ungit/src/config.js:192:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ungit/bin/ungit:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

Have the dependencies for ungit changed? For now I have downgraded to ungit v0.10.3

The following issues mention node 0.11+ may be required:
- [TypeError: Object #<Object> has no method 'execSync'](https://github.com/Kikobeats/oh-my-terminal/issues/1)
- [Fails on Node 0.10 - child process has no method 'execSync'](https://github.com/lerna/lerna/issues/157)

**Comment by evanoloughlin** [comment]
I have updated my installation (versions below) and now its working as expected. Thanks

Versions
- ungit : 1.0.0
- node : v4.7.1
- npm : 2.15.11
- OS: ubuntu 14.04
