### ISSUE TITLE
'YError: Invalid second argument' when starting ungit 1.1.12

### ISSUE THREAD

**Issue by dregad** [FredrikNoren/ungit#896]
I upgraded ungit this morning, and the error mentioned in title occurs 4 times in the startup process. I did not get these errors with 1.1.11. Other than that, everything seems to work normally.

Full stack trace
```
info: BugTracker set version: 1.1.12
info: BugTracker set user hash
YError: Invalid second argument. Expected string but received boolean.
    at argumentTypeError (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/ungit/node_modules/yargs/lib/argsert.js:70:9)
    at /home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/ungit/node_modules/yargs/lib/argsert.js:52:39
    at Array.forEach (native)
    at module.exports (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/ungit/node_modules/yargs/lib/argsert.js:45:21)
    at Object.Yargs.self.describe (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/ungit/node_modules/yargs/yargs.js:263:5)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/ungit/src/config.js:147:2)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by dregad** [comment]
Thanks for the fix and the fast turnaround. I confirm that 1.1.13 fixes the issue :+1:
